meta:
  title: "Political Shifts"
  copyright:
    author: "Jay Draper"
    contact: "@jay_jaydraper"
    title: "The Toolkit: Politics: Part One"
    url: "http://www.madadventurers.com/the-toolkit-politics-part-one/"
  generate: 1
  start: "results"

faction:
  - "Baron Fryr of Drakehold"
  - "Baron Kraus of Leffenmark "
  - "Baron Odern of Khelistead"
  - "Baron Vlad of Eisenhaus"
  - "Baroness Delphine of Auldorf"
  - "Baroness Joselyn of Kellinhaven"
  - "Baroness Pheira of Ivanstead"
  - "Clan Grogfist"
  - "Cloister of Eulogy"
  - "Dragon Isles Privateers"
  - "Dragon Priesthood of Gallowbrook"
  - "Duchess Pike of Dramberg"
  - "Dwarven Sovereignty of Nizmak"
  - "Elves of the Northern Reaches"
  - "Faithful of Leviathan"
  - "First Temple of the Chorus"
  - "Five Great Families "
  - "Freidwarrow Clans"
  - "Great House D'lar"
  - "Great House Galonodel"
  - "Great House Morkai of Valeoth"
  - "Guild of Artisans"
  - "Guild of Carpenters"
  - "Guild of Merchants"
  - "Guild of Smiths"
  - "Holy Sceptre of the God King"
  - "House Dellion of Amaldin"
  - "House Dion of Worthe"
  - "House Grennen of the Northern Kingdoms"
  - "House Merle of the Northern Kingdoms"
  - "House Strielm of Morwald"
  - "House Targh of the Northern Kingdoms"
  - "House Vesci of Amaldin"
  - "House Wellsmere of Adensea"
  - "Local Guild (Within territory belonging to [Faction])"
  - "Magisters of Amaldin"
  - "Miithan Church"
  - "Northern Kingdoms Rebels"
  - "Reformed Temple of the Chorus"
  - "Rhoneid Society"
  - "Sanctii Tribes of the Northern Reaches"
  - "The Free Halflings"
  - "Waymeet Academy"
  - "Witchkin of Channochaide"

relationship:
  - "[Faction:F1] signs a trade treaty with [Faction:F2] causing [Consequence]."
  - "[Faction:F1] closes roads against travellers coming from [Faction:F2] causing [Consequence] and [Consequence]."
  - "[Faction:F1] signs an alliance covenant with [Faction:F2] and [Faction:F3], causing [Consequence], [Consequence], and [Consequence]."
  - "[Faction:F1] signs a treaty with [Faction:F2] causing [Consequence]."
  - "[Faction:F1] establishes a foothold in the territory of [Faction:F2] causing [Consequence] and [Consequence]."
  - "[Faction:F1] restricts trade on all borders, adding an additional 2d8gp tax per ton of cargo causing [Consequence]."
  - "[Faction:F1] restricts trade on 1d4 borders, adding an additional 2d8gp tax per ton of cargo causing [Consequence]."
  - "[Faction:F1] doubles import tariffs on merchants coming from [Faction:F2] causing [Consequence] and [Consequence]."
  - "[Faction:F1] allies with [Faction:F2] against [Faction:F3] causing [Consequence] and [Consequence]."
  - "[Faction:F1] establishes embassy in territory of [Faction:F2] causing [Consequence]."
  - "[Faction:F1] dispatches armed forces into territory of [Faction:F2] causing [Consequence]."
  - "[Faction:F1] closes embassy in territory of [Faction:F2] due to [Consequence]."
  - "[Faction:F1] grants land to [Faction:F2] causing [Consequence]."
  - "[Faction:F1] annexes land belonging to [Faction:F2] causing [Consequence]."
  - "[Faction:F1] waives import tariffs on merchants coming from [Faction:F2] causing [Consequence]."
  - "[Faction:F1] recruits a treasured agent or courtier of [Faction:F2] causing [Consequence]."
  - "[Faction:F1] loses a treasured agent or courtier to [Faction:F2] due to [Consequence]."
  - "[Faction:F1] incurs a debt of 1d20 x 1000gp to [Faction:F2]."
  - "[Faction:F1] signs armistice treaty with [Faction:F2]."
  - "[Faction:F1] plans the assassination of the leading figure(s) of [Faction:F2], with a 25% chance of success."
  - "[Faction:F1] embargoes the main export of [Faction:F2] causing [Consequence]."
  - "[Faction:F1] invades territory of [Faction:F2] causing [Consequence]."
  - "[Faction:F1] publicly denounces [Faction:F2] to their allies, causing ... [Consequence]."
  - "[Faction:F1] introduces new export to [Faction:F2] causing [Consequence]."
  - "[Faction:F1] denies export to [Faction:F2] causing [Consequence]."
  - "[Faction:F1] experiences an influx of refugees or immigrants from [Faction:F2] causing [Consequence]."
  - "[Faction:F1] blocks travel between [Faction:F2] and [Faction:F3], causing [Consequence]."
  - "[Faction:F1] sends officials past borders of [Faction:F2]. with 25% chance of causing [Consequence]."
  - "[Faction:F1] sends Declaration of War to [Faction:F2], causing [Consequence]."
  - "[Faction:F1] sends Declaration of War to [Faction:F2] and [Faction:F3], causing [Consequence] and [Consequence]."
  - "[Faction:F1] foments rebellion amongst the populace of [Faction:F2] causing [Consequence] and [Consequence]."
  - ""
  - "[Faction:F1] enters into a favourable marriage alliance with [Faction:F2], causing either [Consequence] or [Consequence], whichever is more favourable."
  - "[Faction:F1] enters into an unfavourable marriage alliance with [Faction:F2], causing either [Consequence] or [Consequence], whichever is least favourable."
  - "[Faction:F1] sends aid in the form of money, goods or personnel to [Faction:F2], causing either [Consequence] or [Consequence], whichever is more favourable."
  - ""
  - "[Faction:F1] .enters into alliance with [Faction:F2] and [Faction:F3], against [Faction], causing [Consequence] and [Consequence]."
  - "[Faction:F1] dismisses current ambassador to [Faction:F2] and replaces them, causing [Consequence]."
  - "[Faction:F1] introduces an additional levy tax of 1d10sp per month on emigrants from [Faction:F2], causing [Consequence] and [Consequence]. "
  - "[Faction:F1] sends a gift worth 2d10 x 1000gp to [Faction:F2] with the hopes of founding an alliance, with a 50% chance of success."
  - "[Faction:F1] establishes a truce with any hostile territories for 1d4 months, with a 50% chance of successfully maintaining truce."
  - "[Faction:F1] plans the assassination of the leading figure(s) of [Faction:F2], with a 75% chance of success."
  - "[Faction:F1] manipulates hostilities between [Faction:F2] and [Faction:F3], causing [Consequence]."
  - "[Faction:F1] finds one of their agents has sworn a vendetta against the leader(s) of [Faction:F2], with 60% chance of encouraging this vendetta. This causes [Consequence]."
  - "[Faction:F1] finds one of their exports has become popular in territory of [Faction:F2], bringing in additional revenue to their merchants and causing [Consequence]."
  - "[Faction:F1] sends spies into territory of [Faction:F2] due to [Consequence], causing [Consequence]."

consequence:
  - "bandit activity on borders of [F1]'s territory"
  - "prices of [F1]'s exports rise in surrounding regions"
  - "prices of [F2]'s exports rise in [F1]'s region"
  - "a Relationship shift between [F2] and [Faction]"
  - "value of [F1]'s currency is halved, causing dramatic drop in trade between [F1] and surrounding regions"
  - "a rebellion sparks within [F2]'s territory"
  - "hostilities develop between [F2] and [Faction]"
  - "the first glimmers of a civil war are seen in the [F1]'s territory, splitting the populace in half"
  - "bandit activity on borders of [F2]'s region"
  - "value of [F1]'s currency is doubled, causing dramatic rise in trade between [F1] and surrounding regions"
  - "armed hostilities break out on borders between [F1] and [Faction]"
  - "arms and armour trade between the [F1] and their allies increases"
  - "all trade between [F1] and surrounding regions grinds to a halt"
  - "a rebellion sparks within [F1]'s territory"
  - "trade in the regions surround [F1] increases, particularly bolstering the coffers of [Faction]"
  - "arms and armour trade between the [F1] and their allies decreases"
  - "crime increases in the [F2]'s territory, robberies in particular against individuals sympathetic to [F1]"
  - "trade between [F1] and [Faction] prospers, whilst trade from [Faction] grinds to a halt"
  - "the peasants rejoice"
  - "[Faction] and [Faction] swear emnity on [F1],"
  - "all alliances between the [F1] and their allies are withdrawn"
  - "all alliances between the [F1] and their allies are bolstered, granting them 1d10x1000gp in goods and personnel"
  - "all hostilities against the [F1] are withdrawn"
  - "diplomatic staff employed by the [F1] are withdrawn back to their territory"
  - "an embargo against adventurers, mercenaries and other similar service providers is enforced throughout the [F1]'s territory"
  - "military personnel employed by the [F1] are withdrawn back to their territory"
  - "Charter fees for adventurers, mercenaries and similar service providers within the [F1]'s territory are waived for 1d4 months"
  - "camps of refugees from [F1] begin to form on surrounding borders as 1d10% of citizens leave the region"
  - "fights break out on the streets of the [F1]'s territory, public order becomes but a distant memory"
  - "martial law is declared within the [F1]'s territory, with loyal soldiers patrolling the streets and enforcing the law with an iron fist"
  - "the [F1] pushes a new export into trade in the surrounding regions, with a 50% chance of succeeding to turn a profit"
  - "[Consequence], and [Consequence]"
  - "all clothing fashions in the [F1]'s territory are abandoned. Entire wardrobes are thrown into the streets, hat sellers are bankrupted, suddenly no-one has the need for riding boots anymore. It's chaos, I tell you, chaos"
  - "nothing happens"
  - "a minor revolt between citizens occurs within the [F1]'s territory"
  - "a general conscription is planned in the [F1]'s territory, enlisting 1d6 x 10% of citizens of appropriate age and fitness"
  - "the [F1]'s leader has a commemorative statue built within their capital"
  - "a parade is planned within the [F1]'s territory, costing 1d20 x 100gp"
  - "food supplies run dangerously low in the [F1]'s territory"
  - "food supplies are abundant in the [F1]'s territory"
  - "a representative of the [F1]'s administration is imprisoned for treason and/or embezzlement"
  - "a diplomatic catastrophe looms, potentially threatening (50% chance) a breakout of hostilities between the [F1] and [F2]"
  - "the [F1]'s administration is bankrupted, public services and expenditure grinds to a halt"
  - "a 1d4 month tax rebate is granted to adventurers, mercenaries and similar service providers by the [F1]"

