meta:
  title: "Fantasy City Generator"
  copyright:
    author: "dokclaw"
    contact: "https://www.reddit.com/user/dokclaw"
    title: "Reddit: Random City Generator"
    url: "https://www.reddit.com/r/worldbuilding/comments/431v4b/random_city_generator/"
  generate: 1
  start: "Settlement"

Settlement:
  - "A [Wealth] [Population], located at a [Temperature] [Location], and inhabited primarily by [SpeciesMix] [PrimarySpecies].\nInfluence level: [Influence]\nTags: [Tag], [Tag], [Tag], [Tag]"

Tag:
  - "Abyss"
  - "Ancient Architecture"
  - "Ancient Lineage"
  - "Ancient Ruins"
  - "Banking"
  - "Bard School"
  - "Civic Pride"
  - "Civic Service"
  - "Civil Disobediance"
  - "Colonized Population"
  - "Crystals"
  - "Daemonic Cult"
  - "Dark Portal"
  - "Dragon's Nest"
  - "Elemental Altar"
  - "Empty Throne"
  - "Endemic Fauna"
  - "Floating City"
  - "Freak Weather"
  - "Gladiatorial Combat"
  - "Gold Rush"
  - "Hanging City"
  - "Hatred"
  - "Hidden Rulers"
  - "Horrific Customs"
  - "Impossible Architecture"
  - "Linguistic Purity"
  - "Magic Abhorrence"
  - "Magic College"
  - "Magic Worship"
  - "Mass Grave"
  - "Mercantile"
  - "Merchant Princes"
  - "Mutants"
  - "Necropolis"
  - "Oasis"
  - "Oracle"
  - "Oral Tradition"
  - "Organic"
  - "Pilgrimage Site"
  - "Planar Abomination"
  - "Planar Embassy"
  - "Police State"
  - "Power Struggle"
  - "Puritan Ethics"
  - "Recent Coup"
  - "Refugees"
  - "Regional Hegemon"
  - "Rigid Culture"
  - "Sealed Menace"
  - "Sentient Vegitation"
  - "Tent City"
  - "The Frontier"
  - "Theocracy"
  - "Thieve's Guild"
  - "Tyranny"
  - "Vampiric Nests"
  - "Vassal"
  - "Walled city"
  - "Warring Gangs"

Population:
  - "Hamlet"
  - "Hamlet"
  - "Hamlet"
  - "Village"
  - "Village"
  - "Village"
  - "Village"
  - "Village"
  - "Town"
  - "Town"
  - "Town"
  - "Town"
  - "Town"
  - "Town"
  - "Town"
  - "Town"
  - "Town"
  - "Town"
  - "Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "Large Town"
  - "City"
  - "City"
  - "City"
  - "City"
  - "City"
  - "City"
  - "City"
  - "City"
  - "City"
  - "Metropolis"
  - "Metropolis"
  - "Metropolis"
  - "Metropolis"

Location:
  - "Coast"
  - "Coast"
  - "Hill"
  - "Hill"
  - "Hill"
  - "Mountain"
  - "Mountain"
  - "Plain"
  - "Plain"
  - "Plain"
  - "River"
  - "River"
  - "River"
  - "Subterranean Dwelling"
  - "Swamp"
  - "Swamp"

Temperature:
  - "Cold"
  - "Cold"
  - "Freezing"
  - "Scorched"
  - "Temperate"
  - "Temperate"
  - "Temperate"
  - "Tropical"
  - "Tropical"

SpeciesMix:
  - "Amalgamated"
  - "Cloistered"
  - "Cloistered"
  - "Cloistered"
  - "Cloistered"
  - "Close-minded"
  - "Close-minded"
  - "Neutral"
  - "Neutral"
  - "Neutral"
  - "Neutral"
  - "Receptive"
  - "Receptive"
  - "Receptive"
  - "Xenophobic"
 
PrimarySpecies:
  - "Dwarves"
  - "Dwarves"
  - "Elves"
  - "Elves"
  - "Gnomes"
  - "Gnomes"
  - "Halflings"
  - "Halflings"
  - "Humans"
  - "Humans"
  - "Humans"
  - "Ogres"
  - "Orcs"
  - "Orcs"
  - "Other"

Wealth:
  - "Affluent"
  - "Affluent"
  - "Affluent"
  - "Destitute"
  - "Excessive"
  - "Poor"
  - "Poor"
  - "Prospering"
  - "Prospering"
  - "Prospering"
  - "Prospering"
  - "Prospering"
  - "Thrifty"
  - "Thrifty"
  - "Thrifty"
  - "Thrifty"
  - "Thrifty"

Influence:
  - "1"
  - "1"
  - "1"
  - "2"
  - "2"
  - "2"
  - "2"
  - "2"
  - "2"
  - "3"
  - "3"
  - "3"
  - "3"
  - "3"
  - "3"
  - "3"
  - "4"
  - "4"
  - "4"
  - "4"
  - "4"
  - "4"
  - "4"
  - "5"
  - "5"
  - "5"

